# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Materias\2022Q2\Labo de Micros\TPs\App_mp3\ui\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MiMP3(object):
    def setupUi(self, MiMP3):
        MiMP3.setObjectName("MiMP3")
        MiMP3.resize(753, 444)
        self.centralwidget = QtWidgets.QWidget(MiMP3)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.comboBox_COMports = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_COMports.setObjectName("comboBox_COMports")
        self.horizontalLayout_4.addWidget(self.comboBox_COMports)
        self.Btn_buscar = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_buscar.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Btn_buscar.setObjectName("Btn_buscar")
        self.horizontalLayout_4.addWidget(self.Btn_buscar)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_2.addWidget(self.line_4)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.treeView = QtWidgets.QTreeView(self.centralwidget)
        self.treeView.setEnabled(True)
        self.treeView.setMinimumSize(QtCore.QSize(200, 0))
        self.treeView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.treeView.setProperty("showDropIndicator", False)
        self.treeView.setDragEnabled(True)
        self.treeView.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.treeView.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.treeView.setAlternatingRowColors(True)
        self.treeView.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.treeView.setUniformRowHeights(False)
        self.treeView.setHeaderHidden(True)
        self.treeView.setExpandsOnDoubleClick(True)
        self.treeView.setObjectName("treeView")
        self.verticalLayout_2.addWidget(self.treeView)
        self.Btn_agregar = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_agregar.setObjectName("Btn_agregar")
        self.verticalLayout_2.addWidget(self.Btn_agregar)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.Btn_conectar = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_conectar.setObjectName("Btn_conectar")
        self.horizontalLayout_7.addWidget(self.Btn_conectar)
        self.Btn_desconectar = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_desconectar.setObjectName("Btn_desconectar")
        self.horizontalLayout_7.addWidget(self.Btn_desconectar)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_3.addWidget(self.line_5)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listWidget.setProperty("showDropIndicator", False)
        self.listWidget.setDragEnabled(True)
        self.listWidget.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.listWidget.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_3.addWidget(self.listWidget)
        self.Btn_eliminar = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_eliminar.setObjectName("Btn_eliminar")
        self.verticalLayout_3.addWidget(self.Btn_eliminar)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Btn_prev = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_prev.sizePolicy().hasHeightForWidth())
        self.Btn_prev.setSizePolicy(sizePolicy)
        self.Btn_prev.setMinimumSize(QtCore.QSize(100, 100))
        self.Btn_prev.setMaximumSize(QtCore.QSize(100, 100))
        self.Btn_prev.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #555;\n"
"    border-radius: 50px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.Btn_prev.setObjectName("Btn_prev")
        self.horizontalLayout.addWidget(self.Btn_prev)
        self.Btn_play = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_play.sizePolicy().hasHeightForWidth())
        self.Btn_play.setSizePolicy(sizePolicy)
        self.Btn_play.setMinimumSize(QtCore.QSize(100, 100))
        self.Btn_play.setMaximumSize(QtCore.QSize(100, 100))
        self.Btn_play.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #555;\n"
"    border-radius: 50px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.Btn_play.setObjectName("Btn_play")
        self.horizontalLayout.addWidget(self.Btn_play)
        self.Btn_next = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_next.sizePolicy().hasHeightForWidth())
        self.Btn_next.setSizePolicy(sizePolicy)
        self.Btn_next.setMinimumSize(QtCore.QSize(100, 100))
        self.Btn_next.setMaximumSize(QtCore.QSize(100, 100))
        self.Btn_next.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #555;\n"
"    border-radius: 50px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.Btn_next.setObjectName("Btn_next")
        self.horizontalLayout.addWidget(self.Btn_next)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(100, 10))
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.label_song_name = QtWidgets.QLabel(self.centralwidget)
        self.label_song_name.setMaximumSize(QtCore.QSize(16777215, 10))
        self.label_song_name.setObjectName("label_song_name")
        self.horizontalLayout_3.addWidget(self.label_song_name)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.volumeSlider = QtWidgets.QSlider(self.centralwidget)
        self.volumeSlider.setMaximum(32)
        self.volumeSlider.setProperty("value", 32)
        self.volumeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.volumeSlider.setObjectName("volumeSlider")
        self.verticalLayout.addWidget(self.volumeSlider)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.radioButton_normal = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_normal.setChecked(True)
        self.radioButton_normal.setObjectName("radioButton_normal")
        self.horizontalLayout_5.addWidget(self.radioButton_normal)
        self.radioButton_urban = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_urban.setObjectName("radioButton_urban")
        self.horizontalLayout_5.addWidget(self.radioButton_urban)
        self.radioButton_clasical = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_clasical.setObjectName("radioButton_clasical")
        self.horizontalLayout_5.addWidget(self.radioButton_clasical)
        self.radioButton_rock = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_rock.setObjectName("radioButton_rock")
        self.horizontalLayout_5.addWidget(self.radioButton_rock)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        MiMP3.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MiMP3)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 753, 26))
        self.menuBar.setObjectName("menuBar")
        self.menu_Menu = QtWidgets.QMenu(self.menuBar)
        self.menu_Menu.setObjectName("menu_Menu")
        MiMP3.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MiMP3)
        self.statusBar.setSizeGripEnabled(False)
        self.statusBar.setObjectName("statusBar")
        MiMP3.setStatusBar(self.statusBar)
        self.actionClean = QtWidgets.QAction(MiMP3)
        self.actionClean.setObjectName("actionClean")
        self.actionAgregar_todos = QtWidgets.QAction(MiMP3)
        self.actionAgregar_todos.setObjectName("actionAgregar_todos")
        self.menu_Menu.addAction(self.actionClean)
        self.menu_Menu.addAction(self.actionAgregar_todos)
        self.menuBar.addAction(self.menu_Menu.menuAction())

        self.retranslateUi(MiMP3)
        QtCore.QMetaObject.connectSlotsByName(MiMP3)

    def retranslateUi(self, MiMP3):
        _translate = QtCore.QCoreApplication.translate
        MiMP3.setWindowTitle(_translate("MiMP3", "MiMP3"))
        self.label_2.setText(_translate("MiMP3", "Puerto:"))
        self.Btn_buscar.setText(_translate("MiMP3", "Buscar"))
        self.label_4.setText(_translate("MiMP3", "SD:"))
        self.Btn_agregar.setText(_translate("MiMP3", "Agregar seleccionados"))
        self.Btn_conectar.setText(_translate("MiMP3", "Conectar"))
        self.Btn_desconectar.setText(_translate("MiMP3", "Desconectar"))
        self.label_3.setText(_translate("MiMP3", "Lista de reproducción:"))
        self.Btn_eliminar.setText(_translate("MiMP3", "Eliminar seleccionados"))
        self.Btn_prev.setText(_translate("MiMP3", "<"))
        self.Btn_play.setText(_translate("MiMP3", "PLAY"))
        self.Btn_next.setText(_translate("MiMP3", ">"))
        self.label.setText(_translate("MiMP3", "Reproduciendo: "))
        self.label_song_name.setText(_translate("MiMP3", "--"))
        self.radioButton_normal.setText(_translate("MiMP3", "Normal"))
        self.radioButton_urban.setText(_translate("MiMP3", "Urban"))
        self.radioButton_clasical.setText(_translate("MiMP3", "Clasical"))
        self.radioButton_rock.setText(_translate("MiMP3", "Rock"))
        self.menu_Menu.setTitle(_translate("MiMP3", "&Menu"))
        self.actionClean.setText(_translate("MiMP3", "Limpiar lista de reproducción"))
        self.actionAgregar_todos.setText(_translate("MiMP3", "Agregar todos"))
